-- Phonebook feature migration
-- Run this once in Supabase SQL Editor if the GitHub integration does not
-- automatically deploy migrations from the Phonebook directory.

alter table public.phonebook_records
  add column if not exists deleted_at timestamptz;

create index if not exists phonebook_records_deleted_at_idx
  on public.phonebook_records (deleted_at);

create table if not exists public.phonebook_change_log (
  id bigint generated by default as identity primary key,
  record_id uuid,
  action text not null check (action in ('insert', 'update', 'delete', 'restore')),
  before_data jsonb,
  after_data jsonb,
  changed_at timestamptz not null default now()
);

create index if not exists phonebook_change_log_changed_at_idx
  on public.phonebook_change_log (changed_at desc);

create index if not exists phonebook_change_log_record_id_idx
  on public.phonebook_change_log (record_id);

grant select on public.phonebook_change_log to anon, authenticated;

alter table public.phonebook_change_log enable row level security;

drop policy if exists phonebook_change_log_public_read on public.phonebook_change_log;
create policy phonebook_change_log_public_read
on public.phonebook_change_log
for select
to anon, authenticated
using (true);

create or replace function public.log_phonebook_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  event_action text;
begin
  if tg_op = 'INSERT' then
    event_action := 'insert';
    insert into public.phonebook_change_log (record_id, action, after_data)
    values (new.id, event_action, to_jsonb(new));
    return new;
  end if;

  if tg_op = 'UPDATE' then
    if old.deleted_at is null and new.deleted_at is not null then
      event_action := 'delete';
    elsif old.deleted_at is not null and new.deleted_at is null then
      event_action := 'restore';
    else
      event_action := 'update';
    end if;

    insert into public.phonebook_change_log (record_id, action, before_data, after_data)
    values (new.id, event_action, to_jsonb(old), to_jsonb(new));
    return new;
  end if;

  insert into public.phonebook_change_log (record_id, action, before_data)
  values (old.id, 'delete', to_jsonb(old));
  return old;
end;
$$;

drop trigger if exists phonebook_records_log_change on public.phonebook_records;
create trigger phonebook_records_log_change
after insert or update or delete on public.phonebook_records
for each row execute function public.log_phonebook_change();

alter table public.phonebook_records replica identity full;

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'phonebook_records'
  ) then
    execute 'alter publication supabase_realtime add table public.phonebook_records';
  end if;
end;
$$;
